myregistry:
  image: registry:2
  ports:
    - "5000:5000"

myregistrygui:
  image: konradkleine/docker-registry-frontend:v2
  environment:
    - ENV_DOCKER_REGISTRY_HOST=myregistry
    - ENV_DOCKER_REGISTRY_PORT=5000

  ports:
    - "8111:80"
  links:
    - myregistry

